### ISSUE TITLE
Error when setting Helm certificate file

### ISSUE THREAD

**Issue by torbsto** [bakdata/kpops#167]
We have the following default config:

```yaml
kubernetes-app:
  repo_config:
    repository_name: "masekd"
    url: "masked"
    repo_auth_flags:
      username: "masked"
      password: "$CI_JOB_TOKEN"
      ca_file: "/my-cert.cert"
```

This results in the error `TypeError: Object of type PosixPath is not JSON serializable` when generating a pipeline. Removing `ca_file`, kpops generates the pipeline correctly, but we can no longer deploy it.
