### ISSUE TITLE
Change `topic_name` variable to `output_topic_name`

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#28]
Currently, in the config.yaml we define the default topic names like this:
```yaml
topic_name_config:
  default_error_topic_name: "${pipeline_name}-${component_name}-dead-letter-topic"
  default_output_topic_name: "${pipeline_name}-${component_name}-topic"
```
we use the `${topic_name}` in the `pipeline.yaml`. This internal variable is replaced by the `default_output_topic_name`. The naming of this variable is misleading and should be changed to `${output_topic_name}`.
Like the `${error_topic_name}` variable.
