### ISSUE TITLE
Add linting rules

### ISSUE THREAD

**Issue by sujuka99** [bakdata/kpops#298]
**To be added upon transitioning to [Ruff](https://beta.ruff.rs/docs/)**
_Preceded by #272_

Note that compared to the original project, some rules may be missing from a category due to duplicates in other categories. Still, some rules may not yet be implemented and others never will be as the devs decide against adding them.

(WIP) Example config that applies most sensible rules:

```toml
# E203: whitespace before ':' -- Not PEP8 compliant, black won't correct it
# E501: Line too long -- Clashes with `black`
# D100-D107: Missing docstring for {} -- Not convenient to enforce
# RUF012: type class attrs with `ClassVar` -- Too strict/trigger-happy
ignore = ["E203", "E501", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "RUF012"]
# For a list of all possible rules visit https://beta.ruff.rs/docs/rules/
# Pyflakes(F), pycodestyle(E,W), mccabe(C90), isort(I), pyupgrade(UP), flake8-bugbear(B), flake8-no-pep420(INP), ruff(RUF)
select = ["F", "E", "W", "C90", "I", "D", "UP", "B", "INP", "RUF"]
# Exclude snapshots as they are autogenerated
exclude = ["tests/*snapshots"]
# Don't fix Pyflakes because it deletes useful code sometimes
unfixable = ["F"]
# Show fixes by default
show-fixes = true
# Recognized tags
task-tags = ["TODO", "HACK", "FIXME", "XXX"]
# Group violation messages per file
format = "grouped"
# Used by pyupgrade(UP)
target-version = "py310"
# Rules to ignore per file
```

Preferably we would use `select` to explicitly select all wanted rules to avoid new rules sneaking in uninvited.
