### ISSUE TITLE
Environment variables are not updated after kpops import

### ISSUE THREAD

**Issue by mkcode92** [bakdata/kpops#317]
#217 introduced a wrapper for `os.environ`. This, however, freezes the environment known to kpops to the state when `ENV` is first (transitively) imported. If kpops is called programmatically, changes to `os.environ` after importing kpops are ignored.

Minimal setup:
```
# defaults.yaml
kafka-app:
  app:
    streams:
      brokers: ${broker}
      schemaRegistryUrl: ${schema_registry_url}
```
```
# test/pipeline.yaml
- type: streams-app
  name: test
  to:
    topics:
      ${PIPELINE_PREFIX}topic:
        type: output
```
```
# main.py

import os
import sys
from pathlib import Path

os.environ.update(
    {
        "KPOPS_KAFKA_BROKERS": "http://brokers",
        "KPOPS_SCHEMA_REGISTRY_URL": "http://schema-registry",
        "KPOPS_CONNECT_HOST": "http://connect",
        "KPOPS_REST_PROXY_HOST": "http://rest-proxy",
        "KPOPS_ENVIRONMENT": "dev"
    }
)

# Case 1: NOT expanded
from kpops.cli import main

os.environ["PIPELINE_PREFIX"] = "my-prefix-"

# Case 2: expanded
# from kpops.cli import main

if __name__ == "__main__":
     # this might not be the intended way to call kpops programmatically, though :D 
    sys.argv[1:] = [
        "generate",
        "test/pipeline.yaml",
        "--defaults",
        Path(__file__).parent,
    ]
    main.app()
```
