### ISSUE TITLE
Output of `kpops generate` doesn't pass schema validation

### ISSUE THREAD

**Issue by disrupted** [bakdata/kpops#381]
`kpops generate` writes the enriched pipeline as 
```yaml
components:
  - type: ...
  - ...
```
this means, it violates our schema. The `components` key is an implementation detail that should be hidden.
