### ISSUE TITLE
Support referencing additional output topics from components

### ISSUE THREAD

**Issue by torbsto** [bakdata/kpops#484]
Let's say we have the following pipeline:

```yaml
- type: my-producer
  to:
    topics:
      topic-with-role-1:
        role: role1
      topic-with-role-2:
        role: role2
- type: my-streams
  from:
    components:
      my-producer:
        type: input
```

This doesn't work because from components always uses the output topic and doesn't support output topics with roles. This could be for example changed by adding a new key called `fromRole` (`role` already exists if you want to use specify an additional input topic)

```yaml
- type: my-producer
  to:
    topics:
      topic-with-role-1:
        role: role1
      topic-with-role-2:
        role: role2
- type: my-streams
  from:
    components:
      my-producer:
        type: input
        fromRole: role1
```
