### ISSUE TITLE
Reference output topics of components from other pipelines

### ISSUE THREAD

**Issue by philipp94831** [bakdata/kpops#513]
Currently it is only possible to reference output topics of components within the same pipeline. It would be great to have a mechanism to also reference the output topic of anothers piplines components. A syntax I could imagine would be
```
- type: streams-app
  from:
    components:
      my-component:
        type: input
        pipeline: my/other/pipeline # path to pipeline from pipelines base dir
```

If `pipeline` is omited, the behavior does not change, i.e., a component within the same pipeline is referenced.
