### ISSUE TITLE
Manifest `toSection` as Strimzi `KafkaTopic`

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#537]
Whenever the KPOps mode is configured on `Argo`, the `toSection` should be manifested as Strimzi KafkaTopic CRD.

Example:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```
